# Generated by Django 5.0.7 on 2024-08-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_polluser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='question',
            name='new_field',
            field=models.IntegerField(default=7),
        ),
    ]
