# Generated by Django 5.0.7 on 2024-08-24 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_delete_test_question_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='new_field',
        ),
        migrations.AddField(
            model_name='question',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.polluser'),
        ),
    ]
